console.log('Mod 3 rocks!');
console.log('awesome')
console.log('hooray')
console.log('Friday!')
console.log('Pizza')
console.log('Sushi')
console.log('Fajitas')
console.log('I can git')
console.log('burritos')
console.log('tacos')